spring:
  application:
    name: serviceA

security:
  basic:
    enabled: false

logging:
  level:
    io:
      pivotal:
        sample: debug
---
spring:
  profiles: local

eureka:
  instance:
    prefer-ip-address: true

---
spring:
  profiles: cloud
  cloud:
    services:
      registrationMethod: direct
